version: '3.7'


services:
  web:
    image: main-service
    build: .
    command: bash -c "python3 app.py"
    ports:
      - "5001:5001"
    expose:
      - "5001"
    environment:
      FLASK_DEBUG: 1
