version: '3.7'

networks:
  web:
    external: 
      name: mon_net

services:
  web:
    networks:
      - web
    image: seanhong2000/main-service
    build: .
    command: bash -c "python3 app.py"
    ports:
      - "80:5001"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      FLASK_DEBUG: 1


      # networks:
      #   net:
      #     external: true
